---
- hosts: all
  become: yes
  tasks:
  - name: install maria db
    yum: name=mariadb-server state=latest
    tags:
    - install
    when: ansible_os_family == "RedHat"
  - name: start service
    service: name=mariadb state=started
    tags:
    - start
    when: ansible_os_family == "RedHat"
